server:
  port: 8092

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/food
    username: postgres
    password: vini4222
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true